#!/usr/bin/env python3
"""
============================================================================
🚀 SETUP SCRIPT FOR RAG CHATBOT
============================================================================
This script helps you set up the entire RAG system from scratch
Run: python setup.py
============================================================================
"""

import os
import json
import requests
from pathlib import Path
from getpass import getpass
from typing import Dict, List
from requests.auth import HTTPBasicAuth
import urllib3

# Disable SSL warnings
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

class RAGSetup:
    """Setup wizard for RAG chatbot"""
    
    def __init__(self):
        self.config = {}
        
    def welcome(self):
        """Show welcome message"""
        print("=" * 80)
        print("🚀 RAG CHATBOT SETUP WIZARD")
        print("=" * 80)
        print("\nThis wizard will help you set up your RAG chatbot system.\n")
        
    def collect_config(self):
        """Collect configuration from user"""
        
        print("\n📝 Step 1/4: OpenAI Configuration")
        print("-" * 80)
        self.config["OPENAI_API_KEY"] = getpass("Enter your OpenAI API key: ")
        
        print("\n🔍 Step 2/4: OpenSearch Configuration")
        print("-" * 80)
        self.config["OPENSEARCH_ENDPOINT"] = input(
            "OpenSearch endpoint [https://localhost:9200]: "
        ) or "https://localhost:9200"
        
        self.config["OPENSEARCH_USER"] = input(
            "OpenSearch username [admin]: "
        ) or "admin"
        
        self.config["OPENSEARCH_PASSWORD"] = getpass(
            "OpenSearch password: "
        ) or "MyPassword123!"
        
        self.config["OPENSEARCH_INDEX"] = input(
            "Index name [thai_financial_docs]: "
        ) or "thai_financial_docs"
        
        print("\n📄 Step 3/4: Document Sources")
        print("-" * 80)
        print("Enter document URLs (one per line, empty line to finish):")
        
        sources = []
        while True:
            url = input("> ")
            if not url:
                break
            sources.append(url)
        
        self.config["DOCUMENT_SOURCES"] = sources
        
        print("\n⚙️ Step 4/4: Model Configuration")
        print("-" * 80)
        
        models = ["gpt-4o", "gpt-4-turbo", "gpt-3.5-turbo"]
        print("Available models:")
        for i, model in enumerate(models, 1):
            print(f"  {i}. {model}")
        
        choice = input("Select model [1]: ") or "1"
        self.config["OPENAI_MODEL"] = models[int(choice) - 1]
        
    def save_env_file(self):
        """Save configuration to .env file"""
        
        env_content = f"""# RAG Chatbot Configuration
# Generated by setup.py

OPENAI_API_KEY={self.config['OPENAI_API_KEY']}
OPENSEARCH_ENDPOINT={self.config['OPENSEARCH_ENDPOINT']}
OPENSEARCH_USER={self.config['OPENSEARCH_USER']}
OPENSEARCH_PASSWORD={self.config['OPENSEARCH_PASSWORD']}
OPENSEARCH_INDEX={self.config['OPENSEARCH_INDEX']}
OPENAI_MODEL={self.config['OPENAI_MODEL']}
"""
        
        with open(".env", "w") as f:
            f.write(env_content)
        
        print("\n✅ Configuration saved to .env")
    
    def test_opensearch(self) -> bool:
        """Test OpenSearch connection"""
        
        print("\n🔌 Testing OpenSearch connection...")
        
        try:
            response = requests.get(
                self.config["OPENSEARCH_ENDPOINT"],
                auth=HTTPBasicAuth(
                    self.config["OPENSEARCH_USER"],
                    self.config["OPENSEARCH_PASSWORD"]
                ),
                verify=False,
                timeout=5
            )
            
            if response.status_code == 200:
                print("✅ OpenSearch connection successful!")
                return True
            else:
                print(f"❌ OpenSearch connection failed: {response.status_code}")
                return False
                
        except Exception as e:
            print(f"❌ Error connecting to OpenSearch: {str(e)}")
            return False
    
    def create_index(self) -> bool:
        """Create OpenSearch index with proper mappings"""
        
        print("\n📊 Creating OpenSearch index...")
        
        index_settings = {
            "settings": {
                "index": {
                    "knn": True,
                    "knn.algo_param.ef_search": 100,
                    "number_of_shards": 1,
                    "number_of_replicas": 0
                },
                "analysis": {
                    "analyzer": {
                        "thai_analyzer": {
                            "type": "custom",
                            "tokenizer": "thai",
                            "filter": ["lowercase", "stop"]
                        }
                    }
                }
            },
            "mappings": {
                "properties": {
                    "content": {
                        "type": "text",
                        "analyzer": "thai_analyzer"
                    },
                    "embedding": {
                        "type": "knn_vector",
                        "dimension": 1536,  # text-embedding-3-small
                        "method": {
                            "name": "hnsw",
                            "space_type": "cosinesimil",
                            "engine": "lucene"
                        }
                    },
                    "metadata": {
                        "type": "object"
                    }
                }
            }
        }
        
        try:
            # Delete existing index
            requests.delete(
                f"{self.config['OPENSEARCH_ENDPOINT']}/{self.config['OPENSEARCH_INDEX']}",
                auth=HTTPBasicAuth(
                    self.config["OPENSEARCH_USER"],
                    self.config["OPENSEARCH_PASSWORD"]
                ),
                verify=False
            )
            
            # Create new index
            response = requests.put(
                f"{self.config['OPENSEARCH_ENDPOINT']}/{self.config['OPENSEARCH_INDEX']}",
                json=index_settings,
                auth=HTTPBasicAuth(
                    self.config["OPENSEARCH_USER"],
                    self.config["OPENSEARCH_PASSWORD"]
                ),
                verify=False
            )
            
            if response.status_code in [200, 201]:
                print(f"✅ Index '{self.config['OPENSEARCH_INDEX']}' created successfully!")
                return True
            else:
                print(f"❌ Failed to create index: {response.text}")
                return False
                
        except Exception as e:
            print(f"❌ Error creating index: {str(e)}")
            return False
    
    def download_documents(self):
        """Download and index documents"""
        
        if not self.config.get("DOCUMENT_SOURCES"):
            print("\n⏭️  No document sources provided, skipping...")
            return
        
        print("\n📥 Downloading documents...")
        
        data_dir = Path("./data")
        data_dir.mkdir(exist_ok=True)
        
        for i, url in enumerate(self.config["DOCUMENT_SOURCES"], 1):
            print(f"\n  [{i}/{len(self.config['DOCUMENT_SOURCES'])}] Downloading from {url}...")
            
            try:
                response = requests.get(url, timeout=30)
                response.raise_for_status()
                
                filename = f"document_{i}.md"
                filepath = data_dir / filename
                
                with open(filepath, "w", encoding="utf-8") as f:
                    f.write(response.text)
                
                print(f"  ✅ Saved to {filepath}")
                
            except Exception as e:
                print(f"  ❌ Error: {str(e)}")
    
    def create_streamlit_config(self):
        """Create Streamlit configuration"""
        
        print("\n📝 Creating Streamlit configuration...")
        
        secrets_dir = Path(".streamlit")
        secrets_dir.mkdir(exist_ok=True)
        
        secrets_content = f"""[secrets]
OPENAI_API_KEY = "{self.config['OPENAI_API_KEY']}"
OPENSEARCH_ENDPOINT = "{self.config['OPENSEARCH_ENDPOINT']}"
OPENSEARCH_USER = "{self.config['OPENSEARCH_USER']}"
OPENSEARCH_PASSWORD = "{self.config['OPENSEARCH_PASSWORD']}"
OPENSEARCH_INDEX = "{self.config['OPENSEARCH_INDEX']}"
"""
        
        with open(secrets_dir / "secrets.toml", "w") as f:
            f.write(secrets_content)
        
        print("✅ Streamlit secrets created")
    
    def run(self):
        """Run the setup wizard"""
        
        self.welcome()
        self.collect_config()
        self.save_env_file()
        
        if self.test_opensearch():
            self.create_index()
        
        self.download_documents()
        self.create_streamlit_config()
        
        print("\n" + "=" * 80)
        print("✅ SETUP COMPLETE!")
        print("=" * 80)
        print("\nNext steps:")
        print("1. Install dependencies: pip install -r requirements.txt")
        print("2. Run the app: streamlit run app.py")
        print("\n" + "=" * 80)

if __name__ == "__main__":
    setup = RAGSetup()
    setup.run()
